config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  resources :comments

  devise_for :users
  root :to => redirect('/items')
  resources :items

  
  get '/search' => 'items#search', :as => :search

  get "items/index"
  resources :items do
    get :who_bought, on: :member
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :line_items
  has_many :comments
  has_many :orders, through: :line_items
  mount_uploader :picture, PictureUploader
  before_destroy :ensure_not_referenced_by_any_line_item
  
 

  private

  #Ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
   end
  end
  
  def self.search(manufacturer, category)
      if manufacturer.present? && category.present?    
        where("manufacturer like ?", "%#{manufacturer}%") && where( "category like ?", "%#{category}%") 
    elsif manufacturer.present?
            where("manufacturer like ?", "%#{manufacturer}%")
    elsif category.present?
            where( "category like ?", "%#{category}%")
      end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:search_manufacturer].present? || params[:search_category].present?
      @items = Item.search(params[:search_manufacturer], params[:search_category] ).order("created_at DESC")

    else
      @items = Item.order("created_at DESC")
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def who_bought
    @item = Item.find(params[:id])
    @latest_order = @item.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
      @comments = @item.comments.all
      @comment = @item.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :manufacturer, :price, :category, :picture)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<head>
  <title>Search</title>
</head>
<body>
<%= form_tag(items_path, :method => "get", :class => "navbar-form", :id => "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search_manufacturer, params[:search_manufacturer], :class => "span2", :placeholder => "Search Manufacturer" %>
    </div>
    <div class="input-append">
      <%= text_field_tag :search_category, params[:search_category], :class => "span2", :placeholder => "Search Category" %>

      <input type="submit" id="search" value="Search"/>
    </div>
<% end %>

<%= yield %>
</body>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Price</th>
      <th>Category</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.manufacturer %></td>
        <td><%= item.price %></td>
        <td><%= item.category %></td>
        <td><%= item.picture %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'Add To Cart', line_items_path(item_id: item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @item.manufacturer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@item.picture_url, :width => 100) if @item.picture.present? %>
</p>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.email %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>